#!/bin/bash
# 101-compile: Compiles a Python script into $PYFILEc

echo "Compiling $PYFILE ..."
python3 -m py_compile "$PYFILE"
mv "__pycache__/${PYFILE%.*}.cpython-$(python3 -c 'import sys; print(sys.version_info[0]*10+sys.version_info[1])').pyc" "${PYFILE}c"
